In [2]:
#넘파이 : 배열 다룸, list와 유사(list 속도 느리고 메모리 큼), array 사용
!pip install numpy

You should consider upgrading via the 'C:\Users\user\PycharmProjects\venv\Scripts\python.exe -m pip install --upgrade pip' command.


In [3]:
import numpy as np

In [4]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
type(a)

numpy.ndarray

In [5]:
answer = [1, 2, 3, 4]
for i in range(4) :
    answer[i] = answer[i] * 2
print(answer)

[2, 4, 6, 8]


In [6]:
a * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
data1 = np.array([10, 20, 30])
data2 = np.array([5, 6, 7])

In [13]:
2 * data1 + data2


array([25, 46, 67])

In [14]:
data1 == 20

array([False,  True, False])

In [22]:
data = np.array([[0, 1, 2], [3, 4, 5]])
data

array([[0, 1, 2],
       [3, 4, 5]])

In [23]:
len(data) #행
 #열

2

In [25]:
data = np.array([
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]], 
    [[10, 11, 12], [13, 14, 15], [16, 17, 18]]
])
data

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [19]:
len(data)

2

In [20]:
len(data[0])

3

In [21]:
len(data[0][0])

3

In [26]:
data.ndim

3

In [27]:
data.shape

(2, 3, 3)

In [28]:
data = np.array([0, 1, 2, 3, 4])
data[0]

0

In [29]:
data[4]

4

In [30]:
data = np.array([
    [433, 323, 581],
    [491, 842, 295]
])

In [31]:
data[0][0]

433

In [32]:
data[0, 0]

433

In [33]:
data[1][2]

295

In [37]:
data[0][1:]

array([323, 581])

In [46]:
data[0:2][1:3]

array([[491, 842, 295]])

In [47]:
data[:, 1:]

array([[323, 581],
       [842, 295]])

In [48]:
data = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = np.array([True, False, True, False, True, False, True, False, True, False])

In [49]:
data[idx]

array([0, 2, 4, 6, 8])

In [51]:
data % 3 == 0

array([ True, False, False,  True, False, False,  True, False, False,
        True])

In [52]:
data[data%3==0] # 조건문

array([0, 3, 6, 9])

In [53]:
x = np.array([1, 2, 3])
x.dtype

dtype('int32')

In [57]:
x = np.array([1, 2, 3.0])
x.dtype

dtype('float64')

In [59]:
x = np.array(['a', 1, 'c'])
x.dtype

dtype('<U11')

In [60]:
x = np.array([1, 2, 3], dtype='f')
x.dtype

dtype('float32')

In [61]:
x = np.array([1, 2, 3], dtype = 'U')
x.dtype

dtype('<U1')

In [62]:
np.inf

inf

In [63]:
np.nan

nan

In [64]:
a = np.array([0, 1, -1, 0])
b = np.array([1, 0, 0, 0])
a/b

C:\Users\user\AppData\Local\Temp\ipykernel_12624\3783331871.py:3: RuntimeWarning: divide by zero encountered in divide
  a/b
C:\Users\user\AppData\Local\Temp\ipykernel_12624\3783331871.py:3: RuntimeWarning: invalid value encountered in divide
  a/b


array([  0.,  inf, -inf,  nan])

In [65]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [66]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [68]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [69]:
np.zeros((3, 3, 3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [71]:
np.zeros((2,3), dtype='U')

array([['', '', ''],
       ['', '', '']], dtype='<U1')

In [72]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [75]:
np.empty((4, 3))

array([[1.26516525e-311, 2.81617418e-322, 0.00000000e+000],
       [0.00000000e+000, 1.10343781e-312, 8.75983079e+164],
       [4.71562492e-090, 9.60074708e-071, 3.61296781e+174],
       [5.05232982e-038, 6.48224660e+170, 4.93432906e+257]])

In [78]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [80]:
np.arange(1, 21, 3)

array([ 1,  4,  7, 10, 13, 16, 19])

In [83]:
np.linspace(0, 100, 7)

array([  0.        ,  16.66666667,  33.33333333,  50.        ,
        66.66666667,  83.33333333, 100.        ])

In [85]:
np.logspace(0, 10, 10)

array([1.00000000e+00, 1.29154967e+01, 1.66810054e+02, 2.15443469e+03,
       2.78255940e+04, 3.59381366e+05, 4.64158883e+06, 5.99484250e+07,
       7.74263683e+08, 1.00000000e+10])

In [86]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [87]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [92]:
a = np.arange(12)

In [93]:
a.reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [95]:
n_dim = a.reshape(4, -1)

In [96]:
n_dim

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [97]:
n_dim.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [98]:
a1 = np.ones((2, 3))

In [104]:
a2 = np.zeros((2, 2))

In [105]:
np.hstack((a1, a2))

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [106]:
a1 = np.ones((2, 3))

In [107]:
a2 = np.zeros((3, 3))

In [109]:
np.vstack((a1, a2))

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [111]:
x = np.arange(3)

In [112]:
y = np.arange(5)

In [115]:
X, Y = np.meshgrid(x, y)

In [116]:
[list(zip(i, j)) for i, j in zip(X, Y)]

[[(0, 0), (1, 0), (2, 0)],
 [(0, 1), (1, 1), (2, 1)],
 [(0, 2), (1, 2), (2, 2)],
 [(0, 3), (1, 3), (2, 3)],
 [(0, 4), (1, 4), (2, 4)]]

In [117]:
x = np.array([12, 40, 2, 49, 99, 1, 31])

In [118]:
np.sum(x)

234

In [119]:
x.sum()

234

In [120]:
x.min()

1

In [121]:
x.max()

99

In [122]:
x.argmin()

5

In [123]:
x.argmax()

4

In [125]:
x.mean()

33.42857142857143

In [127]:
np.median(x)

31.0

In [130]:
np.all([True, True, True])

True

In [132]:
np.any([True, False])

True

In [133]:
np.sort(x)

array([ 1,  2, 12, 31, 40, 49, 99])

In [134]:
x.var()

1012.8163265306122

In [136]:
x.std()

31.824775357111513

In [137]:
np.percentile(x, 0)

1.0

In [138]:
np.random.rand(10)

array([0.15700852, 0.8952908 , 0.91292077, 0.87017049, 0.78185971,
       0.97666795, 0.28583081, 0.09846653, 0.01828121, 0.92466545])

In [139]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [143]:
np.random.shuffle(x)
x

array([99, 49,  1,  2, 12, 31, 40])

In [144]:
x = np.array([11, 11, 2, 2, 34, 34])

In [145]:
np.unique(x)

array([ 2, 11, 34])

In [146]:
index, count = np.unique(x, return_counts=True)

In [147]:
count

array([2, 2, 2], dtype=int64)

In [148]:
index

array([ 2, 11, 34])